//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Integrated_Tourism_Management_System
{
    using System;
    using System.Collections.Generic;
    
    public partial class attractionbooking
    {
        public attractionbooking()
        {
            this.vehiclebooking = new HashSet<vehiclebooking>();
        }
    
        public int AttractionBookingID { get; set; }
        public string AttractName { get; set; }
        public Nullable<int> AdultNum { get; set; }
        public Nullable<int> ChildNum { get; set; }
        public Nullable<int> AdultPrice { get; set; }
        public Nullable<int> ChildPrice { get; set; }
        public string Status { get; set; }
        public Nullable<System.DateTime> OrderDate { get; set; }
        public string OrderBy { get; set; }
        public string CustID { get; set; }
    
        public virtual attraction attraction { get; set; }
        public virtual staff staff { get; set; }
        public virtual customer customer { get; set; }
        public virtual ICollection<vehiclebooking> vehiclebooking { get; set; }
    }
}
