//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Integrated_Tourism_Management_System
{
    using System;
    using System.Collections.Generic;
    
    public partial class attraction
    {
        public attraction()
        {
            this.attractionbooking = new HashSet<attractionbooking>();
            this.attractionprice = new HashSet<attractionprice>();
            this.package = new HashSet<package>();
        }
    
        public string AttractName { get; set; }
        public string Duration { get; set; }
        public string Cancellation { get; set; }
        public string AttractPhoto { get; set; }
        public string City { get; set; }
    
        public virtual ICollection<attractionbooking> attractionbooking { get; set; }
        public virtual ICollection<attractionprice> attractionprice { get; set; }
        public virtual ICollection<package> package { get; set; }
    }
}
