//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Integrated_Tourism_Management_System
{
    using System;
    using System.Collections.Generic;
    
    public partial class carrier
    {
        public carrier()
        {
            this.flightschedule = new HashSet<flightschedule>();
        }
    
        public int CID { get; set; }
        public string CarrierName { get; set; }
        public string CarrLogo { get; set; }
        public string IATA { get; set; }
    
        public virtual ICollection<flightschedule> flightschedule { get; set; }
    }
}
