//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Integrated_Tourism_Management_System
{
    using System;
    using System.Collections.Generic;
    
    public partial class customer
    {
        public customer()
        {
            this.attractionbooking = new HashSet<attractionbooking>();
            this.cruisebooking = new HashSet<cruisebooking>();
            this.driverbooking = new HashSet<driverbooking>();
            this.flightbooking = new HashSet<flightbooking>();
            this.hotelbooking = new HashSet<hotelbooking>();
        }
    
        public string CustID { get; set; }
        public string Surname { get; set; }
        public string GivenName { get; set; }
        public Nullable<System.DateTime> DateOfBirth { get; set; }
        public string Gender { get; set; }
        public string Passport { get; set; }
        public string Contact { get; set; }
        public string Nationality { get; set; }
    
        public virtual ICollection<attractionbooking> attractionbooking { get; set; }
        public virtual ICollection<cruisebooking> cruisebooking { get; set; }
        public virtual ICollection<driverbooking> driverbooking { get; set; }
        public virtual ICollection<flightbooking> flightbooking { get; set; }
        public virtual ICollection<hotelbooking> hotelbooking { get; set; }
    }
}
