//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Integrated_Tourism_Management_System
{
    using System;
    using System.Collections.Generic;
    
    public partial class driverbooking
    {
        public int DriverRosterID { get; set; }
        public System.DateTime BookingDate { get; set; }
        public string CustID { get; set; }
        public int VehicleBookingID { get; set; }
    
        public virtual customer customer { get; set; }
        public virtual driverroster driverroster { get; set; }
        public virtual vehiclebooking vehiclebooking { get; set; }
    }
}
