//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Integrated_Tourism_Management_System
{
    using System;
    using System.Collections.Generic;
    
    public partial class driverroster
    {
        public driverroster()
        {
            this.driverbooking = new HashSet<driverbooking>();
        }
    
        public int DriverRosterID { get; set; }
        public string DriverID { get; set; }
        public int TimeSlot { get; set; }
        public string Available { get; set; }
    
        public virtual driver driver { get; set; }
        public virtual ICollection<driverbooking> driverbooking { get; set; }
    }
}
