//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Integrated_Tourism_Management_System
{
    using System;
    using System.Collections.Generic;
    
    public partial class driver
    {
        public driver()
        {
            this.driverroster = new HashSet<driverroster>();
        }
    
        public string DriverID { get; set; }
        public string StaffName { get; set; }
        public string Gender { get; set; }
        public string Center { get; set; }
        public string Email { get; set; }
        public string Pass { get; set; }
        public string Position { get; set; }
        public int Salary { get; set; }
        public string Ctype { get; set; }
        public Nullable<int> Late { get; set; }
        public string SImage { get; set; }
        public string SparePass { get; set; }
    
        public virtual ICollection<driverroster> driverroster { get; set; }
    }
}
