//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Integrated_Tourism_Management_System
{
    using System;
    using System.Collections.Generic;
    
    public partial class equipmentlist
    {
        public int VehicleBookingID { get; set; }
        public string EquipID { get; set; }
        public int EquipNum { get; set; }
        public Nullable<decimal> EquipBookPrice { get; set; }
    
        public virtual equipment equipment { get; set; }
        public virtual vehiclebooking vehiclebooking { get; set; }
    }
}
