//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Integrated_Tourism_Management_System
{
    using System;
    using System.Collections.Generic;
    
    public partial class flightschedule
    {
        public flightschedule()
        {
            this.flightbooking = new HashSet<flightbooking>();
            this.indirect = new HashSet<indirect>();
        }
    
        public int FlightID { get; set; }
        public Nullable<int> Carrier { get; set; }
        public Nullable<System.DateTime> EDD { get; set; }
        public Nullable<System.DateTime> EDA { get; set; }
        public Nullable<System.TimeSpan> ETD { get; set; }
        public Nullable<System.TimeSpan> ETA { get; set; }
        public string Origin { get; set; }
        public string Dest { get; set; }
        public string Aircraft { get; set; }
        public Nullable<int> TravelTime { get; set; }
        public string FlightNo { get; set; }
        public string FlightType { get; set; }
    
        public virtual carrier carrier1 { get; set; }
        public virtual ICollection<flightbooking> flightbooking { get; set; }
        public virtual ICollection<indirect> indirect { get; set; }
    }
}
