//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Integrated_Tourism_Management_System
{
    using System;
    using System.Collections.Generic;
    
    public partial class flightbooking
    {
        public int FlightOrderID { get; set; }
        public Nullable<int> FlightID { get; set; }
        public string FlightNo { get; set; }
        public string FlightClass { get; set; }
        public string FlightType { get; set; }
        public Nullable<int> AdultNum { get; set; }
        public Nullable<int> ChildNum { get; set; }
        public Nullable<int> InfantNum { get; set; }
        public Nullable<decimal> AdultPrice { get; set; }
        public Nullable<decimal> ChildPrice { get; set; }
        public Nullable<decimal> InfantPrice { get; set; }
        public Nullable<System.DateTime> OrderDate { get; set; }
        public string OrderBy { get; set; }
        public string CustID { get; set; }
    
        public virtual customer customer { get; set; }
        public virtual flightschedule flightschedule { get; set; }
        public virtual staff staff { get; set; }
        public virtual flightclass flightclass1 { get; set; }
    }
}
