//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Integrated_Tourism_Management_System
{
    using System;
    using System.Collections.Generic;
    
    public partial class hotelbooking
    {
        public int HotelRoomID { get; set; }
        public System.DateTime Checkin { get; set; }
        public System.DateTime Checkout { get; set; }
        public string CustID { get; set; }
        public Nullable<int> NumNight { get; set; }
        public Nullable<int> NumRoom { get; set; }
        public Nullable<decimal> Price { get; set; }
        public Nullable<System.DateTime> OrderDate { get; set; }
        public string OrderBy { get; set; }
    
        public virtual customer customer { get; set; }
        public virtual hotel_room hotel_room { get; set; }
        public virtual staff staff { get; set; }
    }
}
