//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Integrated_Tourism_Management_System
{
    using System;
    using System.Collections.Generic;
    
    public partial class hotel
    {
        public hotel()
        {
            this.hotel_room = new HashSet<hotel_room>();
        }
    
        public int HotelID { get; set; }
        public string Hotel_chi_name { get; set; }
        public string Hotel_en_name { get; set; }
        public Nullable<decimal> Star { get; set; }
        public Nullable<decimal> Rating { get; set; }
        public string Region { get; set; }
        public string Address { get; set; }
        public string Tel { get; set; }
    
        public virtual ICollection<hotel_room> hotel_room { get; set; }
    }
}
