//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Integrated_Tourism_Management_System
{
    using System;
    using System.Collections.Generic;
    
    public partial class hotel_room
    {
        public hotel_room()
        {
            this.hotelbooking = new HashSet<hotelbooking>();
        }
    
        public int Hotel_roomID { get; set; }
        public string Hotel_chi_name { get; set; }
        public string Hotel_room_name { get; set; }
        public string Hotel_room_size { get; set; }
        public Nullable<int> Max_adult { get; set; }
        public Nullable<int> Max_child { get; set; }
        public string Hotel_room_description { get; set; }
        public Nullable<decimal> Fare { get; set; }
        public Nullable<int> HotelID { get; set; }
    
        public virtual hotel hotel { get; set; }
        public virtual ICollection<hotelbooking> hotelbooking { get; set; }
    }
}
