//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Integrated_Tourism_Management_System
{
    using System;
    using System.Collections.Generic;
    
    public partial class indirect
    {
        public int FlightID { get; set; }
        public int StopNo { get; set; }
        public string Stop { get; set; }
        public Nullable<System.DateTime> EDD { get; set; }
        public Nullable<System.TimeSpan> ETD { get; set; }
        public Nullable<System.DateTime> EDA { get; set; }
        public Nullable<System.TimeSpan> ETA { get; set; }
    
        public virtual flightschedule flightschedule { get; set; }
    }
}
