//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Integrated_Tourism_Management_System
{
    using System;
    using System.Collections.Generic;
    
    public partial class package
    {
        public int PackageNo { get; set; }
        public string Attaction { get; set; }
        public string Package1 { get; set; }
        public Nullable<int> Adult_price { get; set; }
        public Nullable<int> Child_price { get; set; }
    
        public virtual attraction attraction { get; set; }
    }
}
