//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Integrated_Tourism_Management_System
{
    using System;
    using System.Collections.Generic;
    
    public partial class staff
    {
        public staff()
        {
            this.attractionbooking = new HashSet<attractionbooking>();
            this.cruisebooking = new HashSet<cruisebooking>();
            this.flightbooking = new HashSet<flightbooking>();
            this.hotelbooking = new HashSet<hotelbooking>();
            this.vehiclebooking = new HashSet<vehiclebooking>();
        }
    
        public string StaffID { get; set; }
        public string StaffName { get; set; }
        public string Gender { get; set; }
        public string Center { get; set; }
        public string Email { get; set; }
        public string Pass { get; set; }
        public string Position { get; set; }
        public Nullable<decimal> Salary { get; set; }
        public string Ctype { get; set; }
        public Nullable<int> Late { get; set; }
        public string SImage { get; set; }
        public string SparePass { get; set; }
    
        public virtual ICollection<attractionbooking> attractionbooking { get; set; }
        public virtual ICollection<cruisebooking> cruisebooking { get; set; }
        public virtual ICollection<flightbooking> flightbooking { get; set; }
        public virtual ICollection<hotelbooking> hotelbooking { get; set; }
        public virtual ICollection<vehiclebooking> vehiclebooking { get; set; }
    }
}
